### PR TITLE
[setup] Automatically drag-in build-time dependencies. Handle cython extensions transparently.

### PR DESCRIPTION
**Pull request by marscher**
This is very similar to mdtraj/mdtraj#934.

To wrap it up shortly, this is needed if users are trying to install via pip and do not have Cython or Numpy installed. Without this patch this will fail, because these dependencies are missing - with this patch they are installed automatically.

### CODE REVIEW

**Comment by marscher** [comment]
Sorry I messed up the reference to the mdtraj issue: mdtraj/mdtraj#934

**Comment by marscher** [comment]
Travis failed stochasticly?

```
File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/bhmm-0.5.1+5.g4016b18-py2.7-linux-x86_64.egg/bhmm/tests/test_init.py", line 60, in test_discrete_4_2
    assert(np.max(B-Bref) < 0.05 or np.max(B[[1,0]]-Bref) < 0.05)
AssertionError
```

**Comment by jchodera** [comment]
I'm re-running travis.

**Comment by jchodera** [comment]
Succeeded this time!

**Comment by franknoe** [comment]
thanks

Am 06/10/15 um 17:40 schrieb Martin K. Scherer:

> This is very similar to mdtraj/mdtraj#943.
> 
> To wrap it up shortly, this is needed if users are trying to install 
> via pip and do not have Cython or Numpy installed. Without this patch 
> this will fail, because these dependencies are missing - with this 
> patch they are installed automatically.
> 
> ---
> 
> ```
>     You can view, comment on, or merge this pull request online at:
> ```
> 
> https://github.com/bhmm/bhmm/pull/22
> 
> ```
>     Commit Summary
> ```
> - [setup] Automatically drag-in build-time dependencies. Handle
>   cython extensions transparently.
>   
>   ```
>   File Changes
>   ```
> - _M_ setup.py https://github.com/bhmm/bhmm/pull/22/files#diff-0 (32)
>   
>   ```
>   Patch Links:
>   ```
> - https://github.com/bhmm/bhmm/pull/22.patch
> - https://github.com/bhmm/bhmm/pull/22.diff
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/bhmm/bhmm/pull/22.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Pull request merged**
