### PR TITLE
Connectivity handling

### PR DESCRIPTION
**Pull request by franknoe**
Fixes various estimation issues encountered with pathological cases, and fixes some basic convergence problems. Many of these issues are entangled, so this became a quite large PR.
- API change: Changed stationary=True to stationary=False. By default we do not assume that the initial HMM distribution is identical to the stationary one. I think this change is important, because in general we cannot obtain a converging EM algorithm with stationary=True (I don't understand why, but the EM algorithm doesn't generally deliver nondecreasing log-likelihoods in that case). Also I think stationary=True is a very special assumption. When using HMMs to analyze MD data, that data is almost always nonstationary and it makes no sense to force the initial distribution to be equal to the stationary one.
- Maximum-likelihood HMM: Can estimate HMMs with general connectivity structure. This includes weakly connected and disconnected transition matrices. 
- Bayesian HMM: Added option to specify a Dirichlet prior for the initial distribution.
- HMM class: A HMM always possesses an initial distribution. This may be identical to the equilibrium distribution of the hidden transition matrix, but doesn't have to be. In particular, we can have an initial distribution even for hidden transition matrices that don't have a unique stationary distribution.
- HMM class: added several new attributes to analyze the connectivity structure. This also includes a method to get a HMM on a subset of states (e.g. to work with HMMs with multiple disconnected sets of hidden states).
- Discrete HMM initialization: Made it more robust, also allow to initialize nonreversible HMMs.
- Added API helper function lag_observations, to lag and stride given observation trajectories.
- Added lots of tests and improved docs.

### CODE REVIEW

**Comment by franknoe** [comment]
sorry, forgot a commit - hang on.

**Comment by franknoe** [comment]
We need a new msmtools release to fix the remaining failures. @marscher can you do a new patch release of the latest msmtools devel?

**Comment by marscher** [comment]
Will do. Are things merged already?

**Comment by franknoe** [comment]
In msmtools? Yes, you can just release devel.
For bhmm no release yet, a larger refactoring will follow.

Thanks.

Am 29/01/16 um 13:06 schrieb Martin K. Scherer:

> Will do. Are things merged already?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/bhmm/bhmm/pull/29#issuecomment-176723521.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
Alright.

**Comment by franknoe** [comment]
ok. @marscher , how do I restart AppVeyor tests? I haven't found a restart button there.

**Comment by marscher** [comment]
you have to login to get this button (and have the rights to do it). Let 
me check if thats the case.

**Comment by marscher** [comment]
You should be able to restart builds now. Can you give a try please?

**Comment by franknoe** [comment]
That worked in Travis, but in AppVeyor I can't see a button after logging in.

**Comment by franknoe** [comment]
No...
screen shot 2016-01-29 at 14 01 47

**Comment by marscher** [comment]
I had to grant an extra role in Appveyor. Should work now

**Comment by franknoe** [comment]
Still the same screen as above. Also no button when I click on the individual builds.

**Comment by franknoe** [comment]
We can also sort this out next week, just restart the builds yourself for now.

**Comment by franknoe** [comment]
Tests are passing. @jchodera if you have time, I'd be glad if you could have a look. There will be some refactoring in the next PRs. This one fixes some important functional problems.

**Comment by franknoe** [comment]
Merging this now. I have several follow-up changes coming up.

**Pull request merged**
