### PR TITLE
HMM initialization failures, kmeans 64 bit

### PR DESCRIPTION
**Pull request by clonker**
I have now specified the data type by a define and made two kmeans modules: one that works with floats and one that works with doubles. This should fix issue #36.

### CODE REVIEW

**Comment by jchodera** [comment]
Thanks

**Comment by jchodera** [comment]
Was the issue in #36 causing travis tests to fail?  If not, could we also add a test that would catch the previous issue?

**Comment by clonker** [comment]
I guess it could explain the random failures since the centers didnt get initialized meaningfully (in GMMs)

**Comment by franknoe** [comment]
Yes, I think this led to random failures.

Am 06/03/16 um 14:20 schrieb Moritz Hoffmann:

> I guess it could explain the random failures since the centers didnt 
> get initialized meaningfully (in GMMs)
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/bhmm/bhmm/pull/37#issuecomment-192886681.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
Thank you very much Moritz. Looks good.

**Comment by jchodera** [comment]
Guys, can someone tell me if a test was added to catch this problem if it appears again?

**Comment by franknoe** [comment]
There has been a test of GHMM initialization which failed stochastically 
due to this bug. I have added a more explicit test in #38.

> Guys, can someone tell me if a test was added to catch this problem if 
> it appears again?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/bhmm/bhmm/pull/37#issuecomment-192891627.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Pull request merged**
