### PR TITLE
Robust output model

### PR DESCRIPTION
**Pull request by franknoe**
- Made output models more robust by optionally allowing to ignore outliers (observations with 0 probability given the current model - these would otherwise lead to uncaught crashes in the C code). When ignored, the HMM behaves as if the observation hadn't been made.
- Reformatted code to adhere to Python code style standards.
- Deleted unused files.
- Added a release note to the docs

### CODE REVIEW

**Comment by jchodera** [comment]
Wouldn't using a Bayesian outlier detection approach be a better way to do this?  In principle, that should be fully compatible with our current approach.

For example, [this approach](http://jakevdp.github.io/blog/2014/06/06/frequentism-and-bayesianism-2-when-results-differ/#A-Bayesian-Approach-to-Outliers:-Nuisance-Parameters) could be used, with an extra Gibbs sampling step used to update the observation labels.

**Comment by franknoe** [comment]
That could be added. What I have implemented is a mechanism that allows observations to be ignored if their observation probability is actually zero and prevent these events from crashing the program. This is optional, and if you use this option, you can also query the output model if such events did happen. 

More sophisticated ways of deciding what an outlier is could be implemented on top of this.

**Comment by jchodera** [comment]
Sounds good!

**Comment by franknoe** [comment]
BTW, what is your feeling how to handle python module headers? We currently have these things:

```
__author__ = "John D. Chodera, Frank Noe"
__copyright__ = "Copyright 2015, John D. Chodera and Frank Noe"
__credits__ = ["John D. Chodera", "Frank Noe"]
__license__ = "LGPL"
__maintainer__ = "John D. Chodera"
__email__ = "jchodera AT gmail DOT com"
```

which are different between modules and sometimes inconsistent / outdated. I think the global part of this information (e.g. license) can go to the package level. Module contributors are handled by github anyway, so I feel we don't need to keep track of this manually. So if you're OK with this, I would replace the entries above by standard license statement.

**Comment by jchodera** [comment]
Sounds good to me.

**Pull request merged**
