### PR TITLE
removed pyemma dependency

### PR DESCRIPTION
**Pull request by marscher**

### CODE REVIEW

**Comment by franknoe** [comment]
This problem should show up on a local test ...

**Comment by marscher** [comment]
The fan of my laptop is broken, so I'll prefer burning the cpus in the cloud. Sorry.

**Comment by franknoe** [comment]
Please don't push untested PR's. That's just confusing.

Am 13/07/15 um 17:06 schrieb Martin K. Scherer:

> The fan of my laptop is broken, so I'll prefer burning the cpus in the 
> cloud. Sorry.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/bhmm/bhmm/pull/8#issuecomment-120961267.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
now it works. Sorry for the confusion (does it work/ doesn't it?)

**Comment by jchodera** [comment]
Looks good to me!  Let's not forget to change the omnia conda recipe too once we cut a new release update.

**Comment by marscher** [comment]
Am 13.07.2015 um 17:22 schrieb John Chodera:

**Comment by franknoe** [comment]
Let me go through it first.

**Comment by franknoe** [comment]
Looks good. Thanks marscher!

I would suggest to also include the k-means GMM initialization stuff in order to be fully independent of pyemma before cutting a new release.

**Comment by marscher** [comment]
somehow the merged PR with sklearn's import and pyemmas kmeans reference has gone during cleaning up the repo. @jchodera can you have a look?

**Comment by jchodera** [comment]
Can you point me to the PR or commit that went missing?

**Comment by marscher** [comment]
Am 13.07.2015 um 18:01 schrieb John Chodera:

**Pull request merged**
