### PR TITLE
added Appveyor (Windows) CI.

### PR DESCRIPTION
**Pull request by marscher**

### CODE REVIEW

**Comment by marscher** [comment]
@jchodera Do you have a win-32 node in our Jenkins cloud? If so, it would be nice to enable a conda build for that system, so we can also provide win-32 support for bhmm.

**Comment by jchodera** [comment]
We don't have a win node yet for Jenkins.  The https://github.com/omnia-md/conda-recipes repo has appveyor enabled which does the win builds (based on your scheme).

**Comment by jchodera** [comment]
Looks like something is still wrong?

**Comment by marscher** [comment]
It is a compilation failure in the kmeans extension, which I currently
do not understand (it is a tricky branching between Py3 and Py2). We
have this extension since 0.4.2, and the branching works at least for
non broken compilers.

**Comment by marscher** [comment]
now it seems to work.

**Comment by marscher** [comment]
Now it is in a mergeable state. It will still fail because of #20, but we can fix this later.

**Pull request merged**
