### PR TITLE
changes self._stationary to self.is_stationary

### PR DESCRIPTION
**Pull request by ChayaSt**

### CODE REVIEW

**Comment by jchodera** [comment]
Is there a quick test that can be added to catch this again in future if things get out of sync?

**Comment by ChayaSt** [comment]
I can add some tests to check if attributes that are used in functions don't get out of sync.

**Comment by ChayaSt** [comment]
I added some asserts for attributes that are used in other properties.

**Comment by jchodera** [comment]
Thanks!

**Pull request merged**
