### PR TITLE
Py3k

### PR DESCRIPTION
**Pull request by marscher**
- only needed to fix some imports, since you already use absolute imports (the recommended ones) all through the project. 
- adopted kmeans module initialization to be compatible both with python2 and 3.
- enabled py3k in travis build matrix

### CODE REVIEW

**Comment by franknoe** [comment]
I think we are using python 3.4 for msmtools. Is it actually necessary to specify an exact python 3 version?

**Comment by marscher** [comment]
the build failed, because msmtools has not been built for py3 yet (Send a pull request to omnia recipes, to enable the build of py3 binaries).

**Comment by jchodera** [comment]
>  (Send a pull request to omnia recipes, to enable the build of py3 binaries).

We're updating the build system. Stay tuned!

**Comment by marscher** [comment]
Works now. If somebody commits not compatible code, travis will complain.

**Comment by jchodera** [comment]
Awesome, thanks!

**Pull request merged**
